@startuml データマート

node データ集約[
    データ集約
    --
    バッチ処理
    SQL集約関数
]

database データマート[
    データマート
    ----
    小: 全て可視化
    大: レスポンス犠牲
]

node 可視化[
    可視化
    ----
    クロス集計表
    チャート表示
]

データ集約 -ri-> データマート
データマート -ri-> 可視化

@enduml